### ISSUE TITLE
google collab bug affecting nwis_client and _restclient. Throws RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/hydrotools#99]
In google collab instantiating a `RestClient` ( this is implicitly done by `nwis_client.IVDataService` ) will cause a `RuntimeError: This event loop is already running` in `google collab`.  This issue is well documented in the [`jupyter notebook`](https://github.com/jupyter/notebook/issues/3397) repo. In that thread, a work around using `nest_asyncio` was mentioned as shown below. The problem and a solution to this issue as shown below.

## Reproduce Problem
```python
!pip install hydrotools.nwis_client

from hydrotools import nwis_client

client = nwis_client.IVDataService()

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-10-d37c2bf4ee70> in <module>()
----> 1 service = nwis_client.IVDataService()

4 frames

/usr/lib/python3.7/asyncio/base_events.py in _check_runnung(self)
    521     def _check_runnung(self):
    522         if self.is_running():
--> 523             raise RuntimeError('This event loop is already running')
    524         if events._get_running_loop() is not None:
    525             raise RuntimeError(

RuntimeError: This event loop is already running
```

## Solution
```python
!pip install hydrotools.nwis_client


import nest_asyncio
nest_asyncio.apply()

from hydrotools import nwis_client
client = nwis_client.IVDataService()
```

IMO I think the best way to get around this is to `try` `catch` where the [error propagates from](https://github.com/NOAA-OWP/hydrotools/blob/340f473a5516772ae8239071132fd748698ff81e/python/_restclient/hydrotools/_restclient/async_helpers.py#L18) and then try to `import nest_asyncio` and call `nest_asyncio.apply()`. If `nest_asyncio` is not installed, throw a `ModuleNotFoundError` refing this issue and noting to install `nest_asyncio`. Given that this is such an edge case and `nest_asyncio` is required by `nbclient` which is required by `nbconvert` which is required by jupyter `notebook`, it is unlikely that a user will ever not have `nest_asyncio` installed and run into this issue. Before I open a PR to resolve this, I'd like to hear your thoughts @jarq6c.

**Comment by jarq6c** [comment]
Can we make the try/catch specific enough that it only catches this edge case?

**Comment by aaraney** [comment]
I believe so, here is a generic example:

```python
def raise_exception():
    raise Exception("test")


def test_catch():
    try:
        raise_exception()
    except Exception as e:
        if str(e) != "test":
            raise e
        print("caught specific error")


if __name__ == "__main__":
    test_catch()

>>> caught specific error
```

**Comment by aaraney** [comment]
Now down the line if the error message changes this will break, but it is the only alternative I can think of off the top of my head although admittedly it is a little frail.

**Comment by aaraney** [comment]
I reproduced the exception using the bellow snippet:

```python
from hydrotools import nwis_client
import asyncio


async def main():
    await asyncio.sleep(0.01)

    service = nwis_client.IVDataService(enable_cache=False)
    return service.get(sites="01646500")


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main()

Traceback (most recent call last):
  File "nwis_client_loop_already_created_bug.py", line 14, in <module>
    loop.run_until_complete(main())
  File "~/miniconda3/envs/et/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "nwis_client_loop_already_created_bug.py", line 8, in main
    service = nwis_client.IVDataService(enable_cache=False)
  File "~/evaluation_tools_fork/python/nwis_client/hydrotools/nwis_client/iv.py", line 91, in __init__
    self._restclient = RestClient(
  File "~/evaluation_tools_fork/python/_restclient/hydrotools/_restclient/_restclient.py", line 109, in __init__
    self._session = self._add_to_loop(
  File "~/evaluation_tools_fork/python/_restclient/hydrotools/_restclient/async_helpers.py", line 22, in _add_to_loop
    return self._loop.run_until_complete(coro)
  File "~/miniconda3/envs/et/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "~/miniconda3/envs/et/lib/python3.8/asyncio/base_events.py", line 552, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
Exception ignored in: <function RestClient.__del__ at 0x1118ffc10>
Traceback (most recent call last):
  File "~/evaluation_tools_fork/python/_restclient/hydrotools/_restclient/_restclient.py", line 297, in __del__
  File "~/evaluation_tools_fork/python/_restclient/hydrotools/_restclient/_restclient.py", line 291, in close
AttributeError: 'RestClient' object has no attribute '_session'
sys:1: RuntimeWarning: coroutine 'AsyncToSerialHelper._wrap_func_in_coro.<locals>.wr' was never awaited

```
